# Generated by Django 5.0.6 on 2024-06-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('apellido_cliente', models.CharField(max_length=100, verbose_name='Apellido del Cliente')),
                ('telefono_cliente', models.CharField(max_length=15, verbose_name='Teléfono del Cliente')),
                ('correo_cliente', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('apellido_cliente', models.CharField(max_length=100, verbose_name='Apellido del Cliente')),
                ('telefono_cliente', models.CharField(max_length=15, verbose_name='Teléfono del Cliente')),
                ('correo_cliente', models.EmailField(max_length=254, verbose_name='Correo')),
                ('asunto_cliente', models.CharField(max_length=100, verbose_name='Asunto')),
                ('mensaje_cliente', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactanos',
            },
        ),
        migrations.CreateModel(
            name='Especialistas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_especialista', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_especialista', models.CharField(max_length=100, verbose_name='Apellido')),
                ('especialidad_especialista', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('telefono_especialista', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('correo_especialista', models.EmailField(max_length=254, verbose_name='Correo')),
                ('foto_especialista', models.ImageField(blank=True, null=True, upload_to='servicios/fotos/especialistas/', verbose_name='Foto')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Pagina Web')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
            },
        ),
        migrations.CreateModel(
            name='InformacionPagina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('informacion', models.CharField(max_length=300, verbose_name='Información de la página Web')),
                ('acerca', models.TextField(verbose_name='Acerca de la página Web')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Informacion de la Pagina Web',
                'verbose_name_plural': 'Informacion de la Pagina Web',
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_plan', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('descripcion_plan', models.TextField(verbose_name='Descripción del Plan')),
                ('precio_plan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Plan')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion_producto', models.TextField(verbose_name='Descripción del Producto')),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Producto')),
                ('cantidad_disponible_producto', models.PositiveIntegerField(verbose_name='Cantidad de Productos')),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='servicios/imagenes/productos/', verbose_name='Imagen del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_servicio', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion_servicio', models.TextField(verbose_name='Descripción del Servicio')),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Servicio')),
                ('imagen_servicio', models.ImageField(blank=True, null=True, upload_to='servicios/imagenes/servicios/', verbose_name='Imagen del Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('correo', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('telefono_cliente', models.CharField(max_length=15, verbose_name='Teléfono del Cliente')),
                ('correo_cliente', models.EmailField(max_length=254, verbose_name='Correo')),
                ('productos', models.ManyToManyField(blank=True, to='servicios.producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
