# Generated by Django 5.0.3 on 2024-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_cliente_producto_reserva_servicio_delete_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_servicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
