# Generated by Django 5.0.3 on 2024-03-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_imagen_producto_servicio_imagen_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_informacion', models.CharField(max_length=100)),
                ('acerca', models.TextField()),
            ],
        ),
    ]
